out_dir: ./  # 输出目录
url_tag: json # web url tag(json,db(https://github.com/google/go-querystring))
language:  # 语言(English,中 文)
db_tag: gorm # 数据库标签(gorm,db)
simple: false # 简单输出(默认gorm标签不输出)
is_out_sql: false # 是否输出 sql 原信息
is_out_func: false # 是否输出 快捷函数
is_web_tag: true # 是否打web标记(json标记前提条件)
is_foreign_key: true # 是否导出外键关联
is_gui: false # 是否ui模式显示
is_table_name: true # 是否直接生成表名,列名
table_prefix: "" # 表前缀, 如果有则使用, 没有留空
table_names: "" # 指定表名 逗号分割
db_info:
  host: 0.0.0.0 # type=1的时候，host为yml文件全路径
  port: 3306
  username: root
  password: 0123
  type: 0 # 数据库类型:0:mysql , 1:sqlite , 2:mssql